[package]
name = "khqr-fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
khqr-core = { path = "../khqr-core" }

[[bin]]
name = "decode"
path = "fuzz_targets/decode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parse_tlv"
path = "fuzz_targets/parse_tlv.rs"
test = false
doc = false
bench = false

[workspace]
